harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

information/urls.py
from django.urls import path
from .views import *

app_name = 'information'

urlpatterns = [
    path("offers/", OfferView.as_view(), name="offers"),
    path('answers/', AnswerView.as_view(), name='answers'),
    path('answers_comment/', AnswerCommentView.as_view(), name='answers_comment'),
    path('comments/', CommentView.as_view(), name='comments'),
    path('comments/category/<int:category>/', CommentsByCategoryView.as_view(), name='comments_category'),
    path('articles/', ArticlesView.as_view(), name="articles"),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/category/<slug:slug>/', ArticlesByCategoryView.as_view(), name='article_category'),
    path('articles/<slug:slug>/positive_grade/', PositiveGradeArticleView.as_view(), name='positive_grade_article'),
    path('articles/<slug:slug>/negative_grade/', NegativeGradeArticleView.as_view(), name='negative_grade_article'),
]

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

information/models.py
from django.db import models
from users.models import *
from events.models import *
from django.utils.text import slugify
from unidecode import unidecode
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from tinymce.models import HTMLField


class Article(models.Model):
    STATUS_CHOICES = (
        (1, 'Опубликовано'),
        (0, 'Черновик'),
    )
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    text = HTMLField(verbose_name='Текст')
    slug = models.SlugField(unique=True, verbose_name='Адрес страницы')
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        related_name='article',
        null=True,
        blank=True,
        default=None,
        verbose_name='Категория'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    positive_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='plus',
        blank=True,
        verbose_name='Положительные оценки')
    negative_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='minus',
        blank=True,
        verbose_name='Отрицательные оценки')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_by_slug", args=[str(self.slug)])

    def save(self, *args, **kwargs):
        title = self.title.lower().replace(' ', '_')
        slug = slugify(unidecode(title))
        self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True, verbose_name='Адрес страницы'
    )

    def save(self, *args, **kwargs):
        name = self.name.lower().replace(' ', '_')
        slug = slugify(unidecode(name))
        self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("article_by_category", args=[str(self.slug)])

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Offer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='offer',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='offer_answer',
        verbose_name='Ответ'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Предложение, пожелание"
        verbose_name_plural = "Предложения, пожелания"


class Comment(models.Model):
    STATUS_CHOICES = [
        (0, 'На модерации'),
        (1, 'Отклонен'),
        (2, 'Опубликован'),
    ]
    CATEGORY_CHOICES = [
        (0, 'Общая оценка'),
        (1, 'Оценка специалиста'),
        (2, 'Оценка статьи'),
        (3, 'Оценка тренинга'),
    ]
    author = models.ForeignKey(
        'users.MyUser',
        related_name='comment',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='comment_answer',
        verbose_name='Ответ'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')
    category = models.IntegerField(
        choices=CATEGORY_CHOICES,
        default=0,
        verbose_name='Категория отзыва'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )

    def __str__(self):
        return f'{self.category} - {self.text}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Answer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='answer_author',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return f'{self.author.username} - {self.text}'

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

users/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db import models
from tinymce.models import HTMLField


class MyUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='avatars/users',
        blank=True,
        null=True,
        verbose_name='Аватар'
    )
    date_birth = models.DateField(
        blank=True,
        null=True,
        default=None,
        verbose_name='Дата рождения'
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Телефон'
    )
    job_title = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Должность'
    )
    job_speciality = HTMLField(
        blank=True,
        null=True,
        verbose_name='Направления работы'
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Education(models.Model):
    STATUS_CHOICES = [
        (1, 'Высшее образование'),
        (2, 'Повышение квалификации'),
        (3, 'Семинар'),
        (4, 'Обучающий курс'),
        (0, 'Другое'),
    ]
    educational_institution = models.CharField(
        max_length=200,
        verbose_name='Учебное заведение'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    speciality = models.TextField(
        verbose_name='Специальность'
    )
    year = models.CharField(
        max_length=4,
        verbose_name='Год окончания'
    )
    photo = models.ImageField(
        upload_to='diplomes/',
        blank=True,
        null=True,
        verbose_name=''
    )
    psychologist = models.ForeignKey(
        'users.MyUser',
        on_delete=models.CASCADE,
        related_name='psychologist',
        verbose_name='Психолог'
    )

    def __str__(self):
        return f'{self.educational_institution} ({self.status}) - {self.year}'

    class Meta:
        verbose_name = "Образование"
        verbose_name_plural = "Образование"

users/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model
from django import forms
from .models import *


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}),
        label='Email'
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}),
        label='Имя пользователя'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}),
        label='Подтверждение пароля'
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя или email'}),
        label='Имя пользователя'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )


class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'first_name', 'last_name', 'date_birth', 'email', 'phone', 'avatar']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
            'avatar': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class PersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'date_birth', 'email', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email

users/templates/change_password.html
{% extends 'client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    change_password {{ user.username }}
{% endblock %}

{% block client_content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="text-center">Смена пароля</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:client_update' user.pk %}" class="btn btn-danger">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/change_password_personal.html
{% extends 'personal.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    change_password {{ user.username }}
{% endblock %}

{% block personal_content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="text-center">Смена пароля</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:personal_update' user.pk %}" class="btn btn-danger">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/client.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    {{ client.username }}
{% endblock %}

{% block content %}
<h1 class="text-center m-1 text-success fst-italic">Ваш личный кабинет</h1>
<div class="container mx-auto mb-2">
    <div class="row align-items-center">
        {% if user.avatar %}
            <div class="col-md-3 mb-3 align-self-start">
                <img src="{{ user.avatar.url }}" alt="Avatar" class="img-fluid rounded">
            </div>
        {% endif %}
        <div class="{% if user.avatar %}col-md-6{% else %}col-9{% endif %} align-self-start">
            {% block client_content %}
            <div class="row align-items-center">
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Имя пользователя</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{ client.username }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Имя</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if client.first_name %}
                                <p class="card-text">{{ client.first_name }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Фамилия</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if client.last_name %}
                                <p class="card-text">{{ client.last_name }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Дата рождения</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if client.date_birth %}
                                <p class="card-text">{{ client.date_birth }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Адрес электронной почты</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if client.email %}
                                <p class="card-text">{{ client.email }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Телефон</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if client.phone %}
                                <p class="card-text">{{ client.phone }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endblock%}
        </div>
        {% include 'client_menu_include.html' %}
    </div>
</div>
{% endblock %}

users/templates/client_comment.html
{% extends 'client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Отзывы {{ user.username }}
{% endblock %}

{% block client_content %}
    <div class="container">
        <h4 class="card-text text-center text-success fst-italic">Ваши отзывы</h4>
        {% for comment in client_comments %}
            <div class="bg-light m-1 p-3 rounded">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        {{ comment.published_date|date:"d M Y H:i" }}
                    </small>
                    <small class="text-muted">
                        <i class="bi {% if comment.status == 0 %}bi-exclamation-circle text-warning
                                     {% elif comment.status == 1 %}bi bi-x-circle text-danger
                                     {% else %} bi bi-check-circle text-success
                                     {% endif %} me-1"></i>
                        {{ comment.get_status_display }}
                    </small>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-list me-1"></i>
                        {{ comment.get_category_display }}
                    </small>
                </div>
                <div class="mb-2">{{ comment.text }}</div>
            </div>
            {% include 'comment_answer_include.html' %}
        {% endfor %}
    </div>
{% endblock %}

users/templates/client_menu_include.html
<div class="col-md-3 mb-3 align-self-start d-flex flex-column">
    <a href="{% url 'users:client' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-house m-2"></i>Личный кабинет</span>
    </a>
    <a href="{% url 'users:client_update' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_update' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-pencil m-2"></i>Редактировать данные</span>
    </a>
    <a href="{% url 'users:client_comments' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_comments' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-stars m-2"></i>Мои отзывы</span>
    </a>
    <a href="{% url 'information:comments' %}"
       class="btn {% if request.resolver_match.view_name == 'information:comments' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-chat m-2"></i>Мои консультации</span>
    </a>
    <a href="{% url 'information:offers' %}"
       class="btn {% if request.resolver_match.view_name == 'information:offers' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-book m-2"></i>Мои тренинги</span>
    </a>
</div>

users/templates/client_update.html
{% extends 'client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    update {{ user.username }}
{% endblock %}

{% block client_content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-text text-center text-success fst-italic">Измените необходимые данные</h4>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-success m-2">Сохранить</button>
                <a href="{% url 'users:client' user.pk %}" class="btn btn-danger m-2">Отмена</a>
            </div>
        </form>
        <a href="{% url 'users:change_password' %}" class="btn btn-info m-2">Изменить пароль</a>
    </div>
</div>
{% endblock %}

users/templates/login.html
{% extends "base.html" %}

{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
Вход
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4 text-center fst-italic">Вход</h2>
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <form method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Вход</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/personal_update.html
{% extends 'personal.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    update {{ user.username }}
{% endblock %}

{% block personal_content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-text text-center text-success fst-italic">Измените необходимые данные</h4>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-success m-2">Сохранить</button>
                <a href="{% url 'users:personal' user.pk %}" class="btn btn-danger m-2">Отмена</a>
            </div>
        </form>
        <a href="{% url 'users:change_password_personal' %}" class="btn btn-info m-2">Изменить пароль</a>
    </div>
</div>
{% endblock %}