harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

information/urls.py
from django.urls import path
from .views import *

app_name = 'information'

urlpatterns = [
    path("offers/", OfferView.as_view(), name="offers"),
    path('answers/', AnswerView.as_view(), name='answers'),
    path('answers_comment/', AnswerCommentView.as_view(), name='answers_comment'),
    path('comments/', CommentView.as_view(), name='comments'),
    path('comments/category/<int:category>/', CommentsByCategoryView.as_view(), name='comments_category'),
    path('articles/', ArticlesView.as_view(), name="articles"),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/category/<slug:slug>/', ArticlesByCategoryView.as_view(), name='article_category'),
    path('articles/<slug:slug>/positive_grade/', PositiveGradeArticleView.as_view(), name='positive_grade_article'),
    path('articles/<slug:slug>/negative_grade/', NegativeGradeArticleView.as_view(), name='negative_grade_article'),
]

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

information/models.py
from django.db import models
from users.models import *
from events.models import *
from django.utils.text import slugify
from unidecode import unidecode
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from tinymce.models import HTMLField


class Article(models.Model):
    STATUS_CHOICES = (
        (1, 'Опубликовано'),
        (0, 'Черновик'),
    )
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    text = HTMLField(verbose_name='Текст')
    slug = models.SlugField(unique=True, verbose_name='Адрес страницы')
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        related_name='article',
        null=True,
        blank=True,
        default=None,
        verbose_name='Категория'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    positive_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='plus',
        blank=True,
        verbose_name='Положительные оценки')
    negative_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='minus',
        blank=True,
        verbose_name='Отрицательные оценки')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_by_slug", args=[str(self.slug)])

    def save(self, *args, **kwargs):
        title = self.title.lower().replace(' ', '_')
        slug = slugify(unidecode(title))
        self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True, verbose_name='Адрес страницы'
    )

    def save(self, *args, **kwargs):
        name = self.name.lower().replace(' ', '_')
        slug = slugify(unidecode(name))
        self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("article_by_category", args=[str(self.slug)])

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Offer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='offer',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='offer_answer',
        verbose_name='Ответ'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Предложение, пожелание"
        verbose_name_plural = "Предложения, пожелания"


class Comment(models.Model):
    STATUS_CHOICES = [
        (0, 'На модерации'),
        (1, 'Отклонен'),
        (2, 'Опубликован'),
    ]
    CATEGORY_CHOICES = [
        (0, 'Общая оценка'),
        (1, 'Оценка специалиста'),
        (2, 'Оценка статьи'),
        (3, 'Оценка тренинга'),
    ]
    author = models.ForeignKey(
        'users.MyUser',
        related_name='comment',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='comment_answer',
        verbose_name='Ответ'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')
    category = models.IntegerField(
        choices=CATEGORY_CHOICES,
        default=0,
        verbose_name='Категория отзыва'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )

    def __str__(self):
        return f'{self.category} - {self.text}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Answer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='answer_author',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return f'{self.author.username} - {self.text}'

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

information/forms.py
from django import forms
from .models import *
from django.utils.text import slugify
from unidecode import unidecode


class OfferForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Offer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ваше предложение или пожелание'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = ['text', 'category']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True
            }),
            'category': forms.Select(attrs={
                'class': 'form-select', 'required': True
            }),
        }
        labels = {
            'text': 'Ваш отзыв',
            'category': 'Категория отзыва'
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Answer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ответ специалиста'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

information/templates/articles.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Статьи
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between align-items-center
    {% if request.resolver_match.view_name == 'information:articles' and search_query == 'search=' %}d-none{% endif %}">
        <a href="{% url 'information:articles' %}"
           class="btn btn-success d-none m-2 d-md-flex align-items-center">
            <i class="bi bi-arrow-left-circle-fill fs-4"></i>
            <span class="ms-2">К списку публикаций</span>
        </a>
        <a href="{% url 'information:articles' %}"
           class="btn btn-success d-flex m-2 d-md-none align-items-center">
            <i class="bi bi-arrow-left-circle-fill fs-4"></i>
        </a>
    </div>
    <div class="container mx-auto mb-2">
        <h1 class="text-center m-2 text-primary">Статьи, советы и рекомендации наших специалистов</h1>
        <form method="get" action="{% url 'information:articles' %}" class="m-1">
            <div class="input-group mb-3">
                <input type="text" name="search" class="form-control"
                       placeholder="Введите ключевое слово для поиска"
                       value="{{ request.GET.search }}">
                <button class="btn btn-success" type="submit">
                    <i class="bi bi-search text-white"></i>
                    <span class="d-none d-sm-inline ms-1">Поиск</span>
                </button>
            </div>
        </form>
        <div class="row align-items-center">
            <div class="col-md-2 align-self-start d-flex flex-column">
                <h4 class="text-center m-1 text-primary">Категории</h4>
                {% for category in categories %}
                    <div><a href="{% url 'information:article_category' category.slug %}"
                            class="btn
                            {% if request.resolver_match.view_name == 'information:article_category' and request.resolver_match.kwargs.slug == category.slug %}
                            btn-primary{% else %}btn-info{% endif %} btn-block mb-1" style="width: 100%;">
                        {{ category.name }}
                    </a></div>
                {% endfor %}
            </div>
            <div class="col-md-10 align-self-start">
                <div class="row">
                {% for article in articles %}
                    <div class="col-md-6">
                        {% include 'article_preview_include.html' %}
                    </div>
                    {% if forloop.counter|divisibleby:2 %}
                        </div>
                        <div class="row">
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
        {% if page_obj.has_other_pages %}
            {% include 'pagination_include.html' %}
        {% endif %}
    </div>
{% endblock %}

information/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Центр психологической помощи 'Гармония'"/>
    <meta name="keywords" content="Психологическая помощь" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/emblema.jpg' %}"/>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% endblock %}
  </head>

  <body>
    <header style="background-color: #35c0f3;">
    {% block header %}
      <div class="container-fluid d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <img src="{% static 'images/Гармония.png' %}" alt="ЛОГОТИП" style="height: 100px;">
          <h1 class="fst-italic text-start p-2 text-white">Центр психологической помощи "Гармония"</h1>
        </div>
        <span class="text-end p-3 d-flex align-items-center">
          {% if user.is_authenticated %}
            {% if user.avatar %}
              <img src="{{ user.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2" style="max-width: 50px;">
            {% else %}
              <span class="rounded-circle bg-success text-white d-flex align-items-center justify-content-center m-2 fs-5"
                   style="width: 50px; height: 50px;">
                <span>{{ user.username|slice:":1" }}</span>
              </span>
            {% endif %}
            {% if user.is_staff == False %}
              <a class="me-5 text-light fs-5" href="{% url 'users:client' user.pk %}">{{ user.username }}</a>
            {% else %}
              <a class="me-5 text-light fs-5" href="{% url 'users:personal' user.pk %}">{{ user.username }}</a>
            {% endif %}
              <a class="nav-link me-3" href="{% url 'users:logout' %}">
                <span class="badge text-bg-primary fs-6">Выйти</span>
              </a>
          {% else %}
            <a class="nav-link me-3" href="{% url 'users:login' %}">
              <span class="badge text-bg-primary fs-6">Вход</span>
            </a>
            <a class="nav-link me-3" href="{% url 'users:register' %}">
              <span class="badge text-bg-primary fs-6">Регистрация</span>
            </a>
          {% endif %}
        </span>
      </div>
    {% endblock %}
    </header>

    <main>
      <nav>
        {% block nav %}
            {% include 'menu.html' %}
        {% endblock %}
      </nav>
      {% block content %} {% endblock %}
    </main>

    <div class="position-fixed top-0 end-0 w-50 p-3" style="z-index: 11">
      {% if messages %}
        {% for message in messages %}
          <div class="alert {% if message.tags == 'error' %}alert-danger
                      {% elif message.tags == 'success' %}alert-primary{% endif %}
                      alert-dismissible fade show" role="alert" aria-live="assertive" aria-atomic="true">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <footer style="background-color: #35c0f3;">
      {% block footer %}
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-lg-0">
            <h5>Контакты:</h5>
            <ul class="list-unstyled">
              <li>
                <i class="bi bi-telephone-fill"></i> +7 (111) 000-00-00
              </li>
              <li>
                <i class="bi bi-house-fill"></i> г. Севастополь, ул. Айвовая
              </li>
            </ul>
            <h5>Режим работы:</h5>
            <ul class="list-unstyled">
              <li>
                Пн-Пт: <i class="bi bi-clock-fill"></i> 9:00 - 18:00
                <i class="bi bi-basket-fill"></i> 12:00 - 13:00
              </li>
              <li>
                Сб-Вс: <i class="bi bi-clock-fill"></i> 11:00 - 15:00
              </li>
            </ul>
          </div>
          <div class="col-lg-6 col-md-12 mb-4 mb-lg-0">
            <div class="map-container">
              <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af570e5d385249b7ace9bd2e5337d12e7d52fd89cddaef1adc1c9cd2e1ead58be&amp;width=450&amp;height=180&amp;lang=ru_RU&amp;scroll=true"></script>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
    let correctAnswers = 0;
    let timer;
    let timeLeft;

    function startTimer() {
        const timerTextElement = document.getElementById('timer_text');
        const timerElement = document.getElementById('timer');
        timeLeft = parseInt(timerElement.innerText, 10);

        timerTextElement.innerText = `Оставшееся время в секундах:`;
        timerElement.innerText = timeLeft;

        timer = setInterval(() => {
            if (timeLeft > 0) {
                timeLeft--;
                timerElement.innerText = timeLeft;
            } else {
                clearInterval(timer);
                finishTest(correctAnswers); // Завершение теста при истечении времени
            }
        }, 1000);
    }

    function answer(currentQuestionId, totalQuestions, correctAnswer) {

        const selectedAnswer = document.querySelector('input[name="question' + currentQuestionId + '"]:checked');
        if (!selectedAnswer) {
            alert('!!! ВЫ НЕ ВЫБРАЛИ ВАРИАНТ ОТВЕТА !!!');
            return;
        }
        if (selectedAnswer.value === correctAnswer) {
            correctAnswers += 1;
        }
        document.getElementById('question' + currentQuestionId).style.display = 'none';
        if (currentQuestionId < totalQuestions) {
            document.getElementById('question' + (currentQuestionId + 1)).style.display = 'block';
        } else {
            finishTest(correctAnswers);
        }
    }
    function finishTest(correctAnswers) {

        clearInterval(timer);
        const questions = document.querySelectorAll('[id^="question"]');
        questions.forEach(question => {
            question.style.display = 'none';
        });

        const csrfToken = document.getElementById('csrf_token').value;
        const score = correctAnswers;

        const currentUrl = window.location.href;
        const resultUrl = currentUrl + 'result/';

        fetch(resultUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrfToken
            },
            body: JSON.stringify({ score: score })
        })

        .then(response => response.json())
        .then(data => {
            if (data.success) {
                document.getElementById('result-container').style.display = 'block';
                document.getElementById('balls').innerText = `Ваш результат в балах - ${correctAnswers}.`;
                document.getElementById('result').innerHTML = data.result;
            }
        })
    }
    window.onload = function() {
        startTimer();
    };
  </script>
  </body>
</html>

information/templates/comment.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Отзывы
{% endblock %}

{% block content %}
    <div class="container">
        {% if user.is_staff %}
            {% include 'comment_for_personal_include.html' %}
            {% if page_obj.has_other_pages %}
                {% include 'pagination_include.html' %}
            {% endif %}
        {% else %}
            {% include 'comment_for_client_include.html' %}
            {% if page_obj.has_other_pages %}
                {% include 'pagination_include.html' %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

information/templates/comment_for_client_include.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% if user.is_authenticated %}
    {% if is_blacklisted %}
        <h2 class="text-center m-2 text-danger">
            К сожалению, Вы находитесь в черном списке и не можете оставлять отзывы
        </h2>
    {% else %}
        <h1 class="text-center m-2 text-primary">Оцените нашу работу!</h1>
        <form method="post" action="{% url 'information:comments' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="page" value="{{ request.GET.page }}">
            <button type="submit" class="btn btn-sm btn-success m-1">Отправить</button>
        </form>
    {% endif %}
{% else %}
    <h1 class="text-center m-2 text-primary">Отзывы наших клиентов</h1>
    <h5 class="text-center m-2">Вы сможете оставить свой отзыв после регистрации</h5>
{% endif %}
{% for comment in comments %}
    {% if comment.author == user %}
        <div class="m-1 p-3 rounded" style="background-color: #d4edda;">
    {% else %}
        <div class="bg-light m-1 p-3 rounded">
    {% endif %}
        <div class="d-flex justify-content-between align-items-center mb-2">
            <h6 class="mb-0">
                {% if comment.author.avatar %}
                    <img src="{{ comment.author.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2"
                         style="width: 30px; height: 30px;">
                {% else %}
                    <i class="bi bi-person-fill me-1"></i>
                {% endif %}
                    {% if comment.author.username %}
                        {{ comment.author.username }}
                    {% else %}
                        Пользователь удалён
                    {% endif %}
            </h6>
            <small class="text-muted">
                <i class="bi bi-clock me-1"></i>
                {{ comment.published_date|date:"d M Y H:i" }}
            </small>
        </div>
        <small class="text-muted">
            <i class="bi bi-list me-1"></i>
            {{ comment.get_category_display }}
        </small>
        <div class="mb-2">{{ comment.text }}</div>
    </div>
    {% include 'comment_answer_include.html' %}
{% endfor %}

information/templates/comment_for_personal_include.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

<h4 class="text-center m-2 text-primary">Отзывы пользователей:</h4>
    {% for comment in comments %}
        <div class="bg-light other-comment mb-3 p-3 rounded">
            <div class="d-flex justify-content-between align-items-center mb-2">
                <h6 class="mb-0">
                    {% if comment.author.avatar %}
                        <img src="{{ comment.author.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2"
                             style="width: 30px; height: 30px;">
                    {% else %}
                        <i class="bi bi-person-fill me-1"></i>
                    {% endif %}
                    {% if comment.author.username %}
                        {{ comment.author.username }}
                    {% else %}
                        Пользователь удалён
                    {% endif %}
                </h6>
                <small class="text-muted">
                    <i class="bi bi-clock me-1"></i>{{ comment.published_date|date:"d M Y H:i" }}
                </small>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-2">
                <small class="text-muted">
                    <i class="bi bi-list me-1"></i>
                    {{ comment.get_category_display }}
                </small>
                <small class="text-muted">
                    <i class="bi {% if comment.status == 0 %}bi-exclamation-circle text-warning
                                 {% elif comment.status == 1 %}bi bi-x-circle text-danger
                                 {% else %} bi bi-check-circle text-success
                                 {% endif %} me-1"></i>
                    {{ comment.get_status_display }}
                </small>
            </div>
            <div class="mb-2">{{ comment.text }}</div>
            <button class="btn btn-sm btn-info reply-button" data-comment-id="{{ comment.id }}">
                <i class="bi bi-reply"></i> Ответить
            </button>
                <div class="reply-form" id="reply-form-{{ comment.id }}" style="display: none;">
                    <form method="post" action="{% url 'information:answers_comment' %}">
                        {% csrf_token %}
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        {{ answer_form.as_p }}
                        <input type="hidden" name="page" value="{{ request.GET.page }}">
                        <button type="submit" class="btn btn-success">Отправить</button>
                        <button type="button" class="btn btn-danger cancel-button">Отмена</button>
                    </form>
                </div>
                {% include 'comment_answer_include.html' %}
        </div>
    {% endfor %}

information/templates/menu.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block nav %}

<nav class="navbar navbar-expand-lg bg-body-tertiary py-1">
<div class="container-fluid bg-info">
    <div class="d-flex flex-column flex-lg-row justify-content-around p-3">
        {% for item in menu %}
            <a href="{% url item.alias %}"
                class="btn {% if item.alias == page_alias %}btn-success
                           {% else %}btn-primary{% endif %}
                           d-flex align-items-center justify-content-between m-1">
            <span><i class="bi {{ item.icon }} me-2"></i>{{ item.title }}</span>
            </a>
        {% endfor %}
    </div>
</div>
</nav>

{% endblock %}

information/templates/offer_for_client_include.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

<h1 class="text-center m-2 text-primary">Помогите нам стать лучше!</h1>
<p class="fst-italic text-center m-2 fs-5">
    Мы ценим ваше мнение и хотим знать, как можем улучшить наши услуги.
</p>
<p class="fst-italic text-center m-2 fs-5">
    Пожалуйста, поделитесь своими предложениями и пожеланиями.
</p>
{% if is_blacklisted %}
    <h2 class="text-center m-2 text-danger">
        К сожалению, Вы находитесь в черном списке и не можете оставлять предложения
    </h2>
{% else %}
    <form method="post" action="{% url 'information:offers' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="page" value="{{ request.GET.page }}">
        <button type="submit" class="btn btn-sm btn-success m-1">Отправить</button>
    </form>
{% endif %}
{% for offer in offers %}
    <div class="bg-light other-comment mb-3 p-3 rounded">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <small class="text-muted">
                <i class="bi bi-clock me-1"></i>
                {{ offer.published_date|date:"d M Y H:i" }}
            </small>
        </div>
        <div class="mb-2">{{ offer.text }}</div>
    </div>
    {% include 'answer_include.html' %}
{% endfor %}